### ISSUE TITLE
How to use phpcsoxid

### ISSUE THREAD

**Issue by adriankirchner** [OXID-eSales/testing_library#3]
I wonder how to use the shipped `phpcsoxid` command. When executing `phpcsoxid` in my oxvm_eshop instance it reports multiple errors in core classes and it even scans unit tests and smarty cache files.
My goal is to include the `phpcsoxid` command into the travis ci configuration of the oxideshop_ce repository. Therefore I need to know how you internally execute this command (exclude parameters etc.) in order to prevent the travis ci builds from failing.
Is that even possible?

**Comment by ellisv** [comment]
In most cases the whole development would go as modules so you could point
to run phpcs against your modules directory. But if that is not the case,
check out wiki page of phpcs
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Usage#checking-files-and-folders

**Comment by adriankirchner** [comment]
So `phpcsoxid` is not intended to run `phpcs` against the oxid core base but against custom modules only?
It would be nice to use the CodeSniffer in travis ci to check contributions before merging them, what do you think?

**Comment by ellisv** [comment]
Ahh sorry man, I've missed a part that you want to use this tool against
oxid ce repository instead of your own project. Ofcourse it may have its
benefits to add this to travis ci but it really depends on how do you treat
those coding style violation - are they warnings or errors? If they are
warnings it may not make sence to fail a build. So it's up to maintainers
to decide how they want to go about this.

I'd suggest you make a pull request to atleast fire up the discussion on
this.

**Comment by adriankirchner** [comment]
alright, thank you for your answers!
