### ISSUE TITLE
AcceptanceTestCase does not execute onActivate event of a module

### ISSUE THREAD

**Issue by gregorhyneck** [OXID-eSales/testing_library#6]
**Description:** When writing an acceptance test and extending the AcceptanceTestCase, tested modules  get activated (on the contrary whats written in the documentation). Amongst others, the function 
`oxModuleInstaller::_callEvent()`
is called in the end. But this function does not execute the onActivate-event because something with the module autoloader is wrong and it can not find the class of the onActivate Event.

**Steps to reproduce:** Install the oe/oepaypal-module in the modules dir. Change 
`partial_module_paths: oe/oepaypal`
and 
`run_tests_for_modules: true`

 in the test_config.yml. Run the acceptance tests and observe the usage of the oePaypal onActivate function (via exit-function, Debugger etc).

**Comment by sauliusstasiukaitis** [comment]
I updated documentation that at least one module is always active.
https://github.com/OXID-eSales/testing_library/commit/64996cdfbf009e353e83a066697b136416aa3ee1
Module autoloader created a static cache for request with active module list. That's why it was impossible to install and activate the module from testing library during one call. This was fixed in Shop https://github.com/OXID-eSales/oxideshop_ce/commit/2a617a2dc942d4141811aecaf0e24d14baf7259d
